### ISSUE TITLE
DefaultPunditAuthorizer requires `update?` for a record's associations

### ISSUE THREAD

**Issue by arcreative** [venuu/jsonapi-authorization#18] opened 2016-04-22 20:06 UTC
Ran into an issue where I wanted to create a model with a reference to another model, and was setting its belongs_to in the request, as usual, but it's failing because the user doesn't have `update?` privs on the association.  Is this intended?  I realize it's safer than `show?`, but doesn't seem like the more common use case.  

To clarify, this is the equivalent of creating a `Comment` on a `Post` where the `comment.post = post`.  This lib seems to require the user to have `update?` privs to `comment` as well as `post` to create `comment`.  

If this is intentional, perhaps it could be documented a bit better?

**Comment by valscion** [comment] 2016-04-23 09:55
Yeah, that sure is a pickle. This is actually an issue that has cropped up before: See #14 and #15.

> If this is intentional, perhaps it could be documented a bit better?

It's partly intentional. We'd like to be able to authorize that users are authorized to also change the associated model, as technically associating new items to something also changes the other model, even if doesn't touch the table in database for the associated model given a `has_many` situation. This is more a limit of standard Pundit actions.

In the meantime, you can easily create your own authorizer with almost similar implementation to `DefaultPunditAuthorizer`, so you can get your application working :). You're more than welcome to join the discussion in #15 and in fact I'll close this issue as a duplicate of #15.

**Closed by valscion** 2016-04-23 09:55 UTC

**Comment by arcreative** [comment] 2016-04-23 14:38
Ah, makes perfect sense semantically, hadn't considered the parent's has_many.  Will check out the other issue, thanks!

**Comment by valscion** [comment] 2016-08-07 09:14
Please see #30 for a possible solution to this problem. Any input in there is greatly appreciated!
