### ISSUE TITLE
Policies aren't being called

### ISSUE THREAD

**Issue by atainton** [venuu/jsonapi-authorization#85] opened 2017-09-22 08:13 UTC
I have a strange issue where I have copied the instructions in the wiki and implemented them in my app. Unfortunately none my policies are being called for some reason. I have noticed the current user is being set but none of the policies are being called. I am using JSONAPI::Resources as endpoints in my app for my API but I also have none JSONAPI::Resources endpoints. 

Any help or information would be greatly appreciated.

**Comment by valscion** [comment] 2017-09-22 08:42
Hi! Thanks for opening an issue.

Could you please tell me the version of `jsonapi-resources` and `jsonapi-authorization` you are using?

Could you also tell me how you came to the conclusion that none of your policies are being called? For us, they most definitely are being called, and the extensive test suite in this repository also thinks so.

**Comment by atainton** [comment] 2017-09-22 08:52
gem 'jsonapi-resources', '~> 0.8.1'
gem 'jsonapi-authorization', '~> 0.8.2'

`class TaskPolicy < ApplicationPolicy
  ROLES = ["manager", "admin", "user"]
  
  def index?
    puts "--------------------------------"
    puts "--------------------------------"
    user.is_another_service? || user.role?(ROLES) 
  end

  def show?
    user.is_another_service? || user.role?(ROLES) 
  end

  def create?
    user.is_another_service? || user.role?(ROLES) 
  end

  def update?
    user.is_another_service? || user.role?(ROLES) 
  end
end`

By the puts statement, nothing is getting outputted to the server

**Comment by atainton** [comment] 2017-09-22 08:54
Here is my application policy,

`class ApplicationPolicy
  attr_reader :user, :record

  def initialize(user, record)
    puts "--------------------------------"
    @user = user
    @record = record
  end

  def index?
    puts "--------------------------------"
    false
  end

  def show?
    false
  end

  def create?
    false
  end

  def update?
    false
  end

  def destroy?
    false
  end

  def scope
    Pundit.policy_scope!(user, record.class)
  end

  class Scope
    attr_reader :user, :scope

    def initialize(user, scope)
      @user = user
      @scope = scope
    end

    def resolve
      scope
    end
  end
end`

**Comment by valscion** [comment] 2017-09-22 08:56
Have you added

```rb
include JSONAPI::Authorization::PunditScopedResource
```

to your resources?

And have you created `config/initializers/jsonapi-resources.rb` file with this content?

```rb
# config/initializers/jsonapi-resources.rb
JSONAPI.configure do |config|
  config.default_processor_klass = JSONAPI::Authorization::AuthorizingProcessor
  config.exception_class_whitelist = [Pundit::NotAuthorizedError]
end
```

Have you restarted your server after these changes?

**Comment by atainton** [comment] 2017-09-22 08:58
Yes, I have.

**Comment by valscion** [comment] 2017-09-22 08:58
Can you tell me what exact versions of `jsonapi-resources` and `jsonapi-authrozization` you have? They are found in Gemfile.lock file

**Comment by atainton** [comment] 2017-09-22 09:01
jsonapi-authorization (0.8.2)
jsonapi-resources (0.8.3)

**Comment by valscion** [comment] 2017-09-22 09:01
And are you sure you are not overriding your processor class on a resource level, or in any other place? I don't think this is an issue with our code, more like something is configured weirdly in your app config.

I'm sorry that I can't be of more help :(. I don't have visibility to your application configuration.

**Comment by valscion** [comment] 2017-09-22 09:02
I've helped debugging this issue to the best of my abilities, and if you could add breakpoints to various places in the code and figure out more details on what is and isn't being called, then I might be able to help more.

Right now, I can't help you more than I've already tried to help 😞

**Comment by atainton** [comment] 2017-09-22 09:06
All good thanks for the help, what do you mean not overriding your processor class on a resource level? Maybe a good place to investigate.

**Comment by atainton** [comment] 2017-09-22 09:11
So I have found the issue I have this class: 
`class V1::TaskProcessor < JSONAPI::Processor
  attr_reader :task
  attr_writer :create_and_publish_event_service_service

  after_replace_fields do
    if attributes.dig(:task_status) == 'Closed'
      create_and_publish_event_service.call(task: task, event_name: 'Dependent Task Complete', topic_name: 'dependent-task-complete')
    end
  end

  def attributes
    @attributes = params.dig(:data, :attributes)
  end

  def task
    @task = result.resource._model
  end

  def create_and_publish_event_service
    @create_and_publish_event_service ||= ::Events::CreateAndPublishEvent.new
  end
end
`
When I remove this class it hits the policy, any way to get around it?

**Comment by atainton** [comment] 2017-09-22 09:15
Thanks for your help you have helped me solve my issue.

If you're using custom processors, make sure that they extend JSONAPI::Authorization::AuthorizingProcessor, or authorization will not be performed for that resource.

**Comment by valscion** [comment] 2017-09-22 10:16
Thanks! So this is a duplicate of #84 :) — Would you mind chiming in in #84 if you could help with documenting this caveat in the README?

**Closed by valscion** 2017-09-22 10:16 UTC
Labels: Status: Needs details / reproduction
