### ISSUE TITLE
Creation authorization doesn't work

### ISSUE THREAD

**Issue by nmanolov** [venuu/jsonapi-authorization#72] opened 2017-06-28 15:23 UTC
In [default_pundit_authorizer.rb](https://github.com/venuu/jsonapi-authorization/blob/ae8ddad62e4fd1c6f7a9e97f10949432e3df4334/lib/jsonapi/authorization/default_pundit_authorizer.rb#L111) `pundit.authorize` is used with model class as second argument.

In [pundit](https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L63), however the second argument is expected to be a record.

Thus, I cannot authorize a creation of a model, as the second argument in my policy is a model class.

**Comment by nmanolov** [comment] 2017-06-28 15:26
I suggest adding [`create_resource`](https://github.com/venuu/jsonapi-authorization/blob/ae8ddad62e4fd1c6f7a9e97f10949432e3df4334/lib/jsonapi/authorization/authorizing_processor.rb#L11) callback after the resource has been created in [jsonapi-resources](https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/processor.rb#L216) so that we can work with it.

**Comment by valscion** [comment] 2017-06-28 15:27
Hi,

unfortunately that is by design, as this gem authorizes actions before any changes, even ones to in-memory objects, are done.

This is a common pitfall. Would you be open to figuring out how we could clarify this in the docs?

If you search around issues here, there will be more context. I'm on mobile and can't write much due to RSI in my wrist.

**Comment by nmanolov** [comment] 2017-06-28 15:31
Thanks, I'll read around.

**Comment by valscion** [comment] 2017-06-28 16:07
If you find context, it would help in documenting this tremendously if you could write what you found out in your own words.

Because no matter how hard I try I won't be able to have the same context as people who just stumbled upon this library. 

Even back-linking things here and paraphrasing them would be helpful

**Comment by valscion** [comment] 2018-11-13 07:19
I'll close this as I think relationship authorization works for the use cases discussed here. https://github.com/venuu/jsonapi-authorization/blob/v1.0.0.beta2/docs/relationship-authorization.md

**Closed by valscion** 2018-11-13 07:19 UTC
Labels: Type: Discussion
